// Auto-generated by LibreLane
module fir_filter(
`ifdef USE_POWER_PINS
  inout VPWR,
  inout VGND,
`endif
  input clk,
  input rst_n,
  input[15:0] sample_in,
  input sample_valid,
  output[15:0] result_out,
  output result_valid,
  output ready
);
endmodule
